-- ============================================================
-- PERSEVEX CERTIFICATE HISTORY TABLE SCHEMA
-- Run this in your Supabase SQL Editor to create the table.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.certificate_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificate_id TEXT UNIQUE NOT NULL,
    student_name TEXT NOT NULL,
    student_email TEXT NOT NULL,
    internship_domain TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    issued_date TEXT NOT NULL,
    generated_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    email_status TEXT DEFAULT 'pending', -- 'sent', 'failed', 'pending'
    certificate_status TEXT DEFAULT 'active', -- 'active', 'revoked'
    revocation_reason TEXT,
    sent_at TIMESTAMPTZ,
    send_count INT DEFAULT 0,
    pdf_filename TEXT,
    error_message TEXT,
    template_version TEXT DEFAULT 'v1'
);

-- Safe migration statements if table already exists in Supabase
ALTER TABLE public.certificate_history ADD COLUMN IF NOT EXISTS certificate_status TEXT DEFAULT 'active';
ALTER TABLE public.certificate_history ADD COLUMN IF NOT EXISTS revocation_reason TEXT;
ALTER TABLE public.certificate_history ADD COLUMN IF NOT EXISTS template_version TEXT DEFAULT 'v1';

-- Index for fast lookup by certificate_id (used by public QR verification)
CREATE INDEX IF NOT EXISTS idx_certificate_history_cert_id ON public.certificate_history (certificate_id);

-- Index for searching and filtering
CREATE INDEX IF NOT EXISTS idx_certificate_history_created_at ON public.certificate_history (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_certificate_history_student_email ON public.certificate_history (student_email);
CREATE INDEX IF NOT EXISTS idx_certificate_history_domain ON public.certificate_history (internship_domain);
CREATE INDEX IF NOT EXISTS idx_certificate_history_email_status ON public.certificate_history (email_status);
CREATE INDEX IF NOT EXISTS idx_certificate_history_cert_status ON public.certificate_history (certificate_status);
