-- ============================================================
-- MIGRATION: SEPARATE CAMPUS AMBASSADOR HISTORY TABLE
-- File: migrations/0002_separate_campus_ambassador_history.sql
--
-- PURPOSE:
-- 1. Create public.campus_ambassador_history table.
-- 2. Create optimized indexes for lookups, history filtering, and sorting.
-- 3. Idempotently copy legacy CA records from public.email_history if present.
-- 4. Align the identity sequence to the maximum record ID.
--
-- NOTE:
-- This migration is idempotent and non-destructive.
-- Legacy CA records have been safely migrated and verified.
-- Do NOT execute destructive cleanup automatically in this file.
-- ============================================================

-- ------------------------------------------------------------
-- STEP 1: CREATE TABLE public.campus_ambassador_history
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.campus_ambassador_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    student_email TEXT NOT NULL,
    phone_number TEXT,
    college_name TEXT,
    internship_domain TEXT DEFAULT 'Campus Ambassador',
    internship_duration TEXT DEFAULT 'Tenure',
    start_date TEXT,
    end_date TEXT,
    offer_letter_type TEXT DEFAULT 'campus_ambassador',
    email_status TEXT DEFAULT 'pending',
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    offer_letter_id TEXT,
    pdf_filename TEXT,
    send_count INT DEFAULT 0,
    error_message TEXT
);

-- ------------------------------------------------------------
-- STEP 2: CREATE INDEXES FOR FAST LOOKUP & HISTORY FILTERING
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_ca_history_created_at ON public.campus_ambassador_history (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ca_history_sent_at ON public.campus_ambassador_history (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_ca_history_student_email ON public.campus_ambassador_history (student_email);
CREATE INDEX IF NOT EXISTS idx_ca_history_email_status ON public.campus_ambassador_history (email_status);
CREATE INDEX IF NOT EXISTS idx_ca_history_offer_letter_id ON public.campus_ambassador_history (offer_letter_id);

-- ------------------------------------------------------------
-- STEP 3: MIGRATE LEGACY CA RECORDS FROM email_history
-- (Idempotent: Uses ON CONFLICT (id) DO NOTHING so it can be safely re-run)
-- ------------------------------------------------------------
INSERT INTO public.campus_ambassador_history (
    id,
    student_name,
    student_email,
    phone_number,
    college_name,
    internship_domain,
    internship_duration,
    start_date,
    end_date,
    offer_letter_type,
    email_status,
    sent_at,
    created_at,
    offer_letter_id,
    pdf_filename,
    send_count,
    error_message
)
SELECT
    id,
    student_name,
    student_email,
    phone_number,
    college_name,
    COALESCE(internship_domain, 'Campus Ambassador'),
    COALESCE(internship_duration, 'Tenure'),
    start_date,
    end_date,
    'campus_ambassador',
    COALESCE(email_status, 'pending'),
    sent_at,
    created_at,
    offer_letter_id,
    pdf_filename,
    COALESCE(send_count, 0),
    error_message
FROM public.email_history
WHERE
    LOWER(COALESCE(offer_letter_type, '')) IN ('campus_ambassador', 'ca_letter')
    OR LOWER(COALESCE(internship_domain, '')) = 'campus ambassador'
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- STEP 4: SYNCHRONIZE IDENTITY SEQUENCE
-- ------------------------------------------------------------
SELECT setval(
    pg_get_serial_sequence('public.campus_ambassador_history', 'id'),
    COALESCE((SELECT MAX(id) FROM public.campus_ambassador_history), 1)
);

-- ------------------------------------------------------------
-- STEP 5: VERIFICATION QUERIES (INFORMATIONAL ONLY)
-- ------------------------------------------------------------
-- SELECT count(*) AS total_ca_records FROM public.campus_ambassador_history;
-- SELECT count(*) AS remaining_normal_offers FROM public.email_history;
-- SELECT count(*) AS total_certificates FROM public.certificate_history;

-- ------------------------------------------------------------
-- STEP 6: HISTORICAL CLEANUP NOTE
-- ------------------------------------------------------------
-- Note: Cleanup of legacy CA records from public.email_history was performed
-- manually and verified in production after successful data migration.
-- No active DELETE statement is included here to ensure this migration
-- remains non-destructive and idempotent when executed again:
--
-- Manual cleanup statement (already executed and verified):
-- DELETE FROM public.email_history
-- WHERE LOWER(COALESCE(offer_letter_type, '')) IN ('campus_ambassador', 'ca_letter')
--    OR LOWER(COALESCE(internship_domain, '')) = 'campus ambassador';
