CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.campus_ambassador_certificate_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_name TEXT NOT NULL,
    participant_email TEXT NOT NULL,
    program_date TEXT NOT NULL,
    document_id TEXT UNIQUE NOT NULL,
    pdf_filename TEXT,
    email_status TEXT DEFAULT 'pending',
    sent_at TIMESTAMPTZ,
    send_count INT DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    template_version TEXT DEFAULT 'v1'
);

ALTER TABLE public.campus_ambassador_certificate_history
    ADD COLUMN IF NOT EXISTS claim_token UUID,
    ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_ca_certificate_history_created_at
    ON public.campus_ambassador_certificate_history (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ca_certificate_history_email
    ON public.campus_ambassador_certificate_history (participant_email);
CREATE INDEX IF NOT EXISTS idx_ca_certificate_history_status
    ON public.campus_ambassador_certificate_history (email_status);

CREATE TABLE IF NOT EXISTS public.campus_ambassador_certificate_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    status TEXT NOT NULL DEFAULT 'queued',
    program_date TEXT NOT NULL,
    total_count INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    generated_count INTEGER NOT NULL DEFAULT 0,
    sent_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.campus_ambassador_certificate_job_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID NOT NULL REFERENCES public.campus_ambassador_certificate_jobs(id) ON DELETE CASCADE,
    source_row INTEGER NOT NULL,
    participant_name TEXT NOT NULL,
    participant_email TEXT NOT NULL,
    program_date TEXT NOT NULL,
    generation_status TEXT NOT NULL DEFAULT 'pending',
    email_status TEXT NOT NULL DEFAULT 'pending',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    send_count INTEGER NOT NULL DEFAULT 0,
    document_id TEXT,
    error_message TEXT,
    claim_token UUID,
    claimed_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    UNIQUE(job_id, source_row)
);

CREATE INDEX IF NOT EXISTS idx_ca_cert_job_items_status
    ON public.campus_ambassador_certificate_job_items (job_id, generation_status, email_status);

CREATE OR REPLACE FUNCTION public.claim_ca_certificate_job_items(
    target_job UUID,
    batch_size INTEGER,
    token UUID
) RETURNS SETOF public.campus_ambassador_certificate_job_items
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.campus_ambassador_certificate_job_items
       SET generation_status = 'pending',
           claim_token = NULL,
           claimed_at = NULL,
           updated_at = timezone('utc'::text, now())
     WHERE job_id = target_job
       AND generation_status = 'processing'
       AND claimed_at < timezone('utc'::text, now()) - INTERVAL '10 minutes';

    RETURN QUERY
    UPDATE public.campus_ambassador_certificate_job_items
       SET generation_status = 'processing',
           claim_token = token,
           claimed_at = timezone('utc'::text, now()),
           updated_at = timezone('utc'::text, now())
     WHERE id IN (
         SELECT id
           FROM public.campus_ambassador_certificate_job_items
          WHERE job_id = target_job
            AND generation_status = 'pending'
            AND email_status = 'pending'
          ORDER BY source_row
          LIMIT GREATEST(batch_size, 1)
          FOR UPDATE SKIP LOCKED
     )
    RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_ca_certificate_email_items(
    target_job UUID,
    batch_size INTEGER,
    token UUID,
    retry_failed BOOLEAN DEFAULT FALSE
) RETURNS SETOF public.campus_ambassador_certificate_job_items
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.campus_ambassador_certificate_history AS h
       SET email_status = 'uncertain',
           error_message = 'Delivery outcome unknown after interrupted bulk send; manual reconciliation required.',
           claim_token = NULL,
           claimed_at = NULL
      FROM public.campus_ambassador_certificate_job_items AS i
     WHERE h.document_id = i.document_id
       AND i.job_id = target_job
       AND i.email_status = 'sending'
       AND i.claimed_at < timezone('utc'::text, now()) - INTERVAL '10 minutes';

    UPDATE public.campus_ambassador_certificate_job_items
       SET email_status = 'uncertain',
           error_message = 'Delivery outcome unknown after interrupted send; manual reconciliation required.',
           updated_at = timezone('utc'::text, now())
     WHERE job_id = target_job
       AND email_status = 'sending'
       AND claimed_at < timezone('utc'::text, now()) - INTERVAL '10 minutes';

    RETURN QUERY
    UPDATE public.campus_ambassador_certificate_job_items
       SET email_status = 'sending',
           claim_token = token,
           claimed_at = timezone('utc'::text, now()),
           updated_at = timezone('utc'::text, now())
     WHERE id IN (
         SELECT id
           FROM public.campus_ambassador_certificate_job_items
          WHERE job_id = target_job
            AND generation_status = 'generated'
            AND (
                email_status = 'pending'
                OR (retry_failed AND email_status = 'failed')
            )
          ORDER BY source_row
          LIMIT GREATEST(batch_size, 1)
          FOR UPDATE SKIP LOCKED
     )
    RETURNING *;
END;
$$;

ALTER TABLE public.campus_ambassador_certificate_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campus_ambassador_certificate_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campus_ambassador_certificate_job_items ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.campus_ambassador_certificate_history FROM anon, authenticated;
REVOKE ALL ON TABLE public.campus_ambassador_certificate_jobs FROM anon, authenticated;
REVOKE ALL ON TABLE public.campus_ambassador_certificate_job_items FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campus_ambassador_certificate_history TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campus_ambassador_certificate_jobs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campus_ambassador_certificate_job_items TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.campus_ambassador_certificate_history_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.claim_ca_certificate_job_items(UUID, INTEGER, UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.claim_ca_certificate_email_items(UUID, INTEGER, UUID, BOOLEAN) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_ca_certificate_job_items(UUID, INTEGER, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_ca_certificate_email_items(UUID, INTEGER, UUID, BOOLEAN) TO service_role;

CREATE OR REPLACE FUNCTION public.claim_ca_certificate_single_email(
    p_participant_name TEXT,
    p_participant_email TEXT,
    p_program_date TEXT,
    p_document_id TEXT,
    p_pdf_filename TEXT,
    p_claim_token UUID,
    p_allow_resend BOOLEAN DEFAULT FALSE
) RETURNS TABLE (
    claimed BOOLEAN,
    record_id BIGINT,
    document_id TEXT,
    email_status TEXT,
    send_count INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    normalized_email TEXT := lower(trim(p_participant_email));
    blocked_status TEXT;
    previous_send_count INTEGER;
    inserted_id BIGINT;
    existing_status TEXT;
    existing_send_count INTEGER;
BEGIN
    IF normalized_email = '' OR p_claim_token IS NULL OR p_document_id = '' THEN
        RAISE EXCEPTION 'Participant email, claim token, and document ID are required.';
    END IF;

    PERFORM pg_advisory_xact_lock(hashtextextended(normalized_email, 0));

    UPDATE public.campus_ambassador_certificate_history
       SET email_status = 'uncertain',
           error_message = 'Delivery outcome unknown after interrupted single send; manual reconciliation required.',
           claim_token = NULL,
           claimed_at = NULL
     WHERE lower(trim(participant_email)) = normalized_email
       AND email_status = 'sending'
       AND claimed_at < timezone('utc'::text, now()) - INTERVAL '10 minutes';

    SELECT h.email_status
      INTO blocked_status
      FROM public.campus_ambassador_certificate_history AS h
     WHERE lower(trim(h.participant_email)) = normalized_email
       AND h.email_status IN ('sending', 'uncertain')
     ORDER BY h.created_at DESC
     LIMIT 1;

    IF blocked_status IS NOT NULL THEN
        RETURN QUERY SELECT FALSE, NULL::BIGINT, NULL::TEXT, blocked_status, 0;
        RETURN;
    END IF;

    IF NOT p_allow_resend AND EXISTS (
        SELECT 1
          FROM public.campus_ambassador_certificate_history AS h
         WHERE lower(trim(h.participant_email)) = normalized_email
           AND h.email_status = 'sent'
    ) THEN
        RETURN QUERY SELECT FALSE, NULL::BIGINT, NULL::TEXT, 'sent'::TEXT, 0;
        RETURN;
    END IF;

    SELECT h.id, h.email_status, h.send_count
      INTO inserted_id, existing_status, existing_send_count
      FROM public.campus_ambassador_certificate_history AS h
     WHERE h.document_id = p_document_id
       AND lower(trim(h.participant_email)) = normalized_email
     FOR UPDATE;

    IF inserted_id IS NOT NULL THEN
        IF existing_status NOT IN ('failed', 'sent') THEN
            RETURN QUERY SELECT FALSE, inserted_id, p_document_id, existing_status, existing_send_count;
            RETURN;
        END IF;

        UPDATE public.campus_ambassador_certificate_history
           SET participant_name = trim(p_participant_name),
               program_date = p_program_date,
               pdf_filename = p_pdf_filename,
               email_status = 'sending',
               send_count = existing_send_count + 1,
               error_message = NULL,
               claim_token = p_claim_token,
               claimed_at = timezone('utc'::text, now())
         WHERE id = inserted_id;

        RETURN QUERY SELECT TRUE, inserted_id, p_document_id, 'sending'::TEXT, existing_send_count + 1;
        RETURN;
    END IF;

    SELECT COALESCE(MAX(h.send_count), 0)
      INTO previous_send_count
      FROM public.campus_ambassador_certificate_history AS h
     WHERE lower(trim(h.participant_email)) = normalized_email;

    INSERT INTO public.campus_ambassador_certificate_history (
        participant_name, participant_email, program_date, document_id,
        pdf_filename, email_status, send_count, claim_token, claimed_at
    ) VALUES (
        trim(p_participant_name), normalized_email, p_program_date, p_document_id,
        p_pdf_filename, 'sending', previous_send_count + 1, p_claim_token,
        timezone('utc'::text, now())
    )
    RETURNING id INTO inserted_id;

    RETURN QUERY SELECT TRUE, inserted_id, p_document_id, 'sending'::TEXT, previous_send_count + 1;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_ca_certificate_single_email(
    TEXT, TEXT, TEXT, TEXT, TEXT, UUID, BOOLEAN
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_ca_certificate_single_email(
    TEXT, TEXT, TEXT, TEXT, TEXT, UUID, BOOLEAN
) TO service_role;
