-- ============================================================
-- DEVELOPMENT ONLY: BASE HISTORY TABLES PROVISIONING
-- File: migrations/0008_development_base_history_tables.sql
-- Target Database: Development Supabase (vaqleosqgsmnsppnxqbh)
--
-- PURPOSE:
-- Provision missing base tables in development Supabase to establish
-- complete schema parity with production:
--   1. public.email_history (Offer Letters)
--   2. public.campus_ambassador_history (Campus Ambassador Offer Letters)
--   3. public.certificate_history (Internship Certificates)
--
-- SAFETY & COMPLIANCE:
-- - Idempotent (IF NOT EXISTS)
-- - Zero impact on production (production already contains these tables)
-- - Non-destructive (does not drop or alter existing CA Certificate tables)
-- - Aligned with repository contracts in database/repository.py
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABLE: public.email_history (Offer Letters)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.email_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    student_name TEXT,
    student_email TEXT,
    phone_number TEXT,
    college_name TEXT,
    internship_domain TEXT,
    internship_duration TEXT,
    start_date TEXT,
    end_date TEXT,
    offer_letter_type TEXT,
    email_status TEXT DEFAULT 'pending',
    sent_at TIMESTAMPTZ,
    offer_letter_id TEXT,
    pdf_filename TEXT,
    send_count BIGINT DEFAULT 0,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_email_history_created_at ON public.email_history (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_history_sent_at ON public.email_history (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_history_student_email ON public.email_history (student_email);
CREATE INDEX IF NOT EXISTS idx_email_history_email_status ON public.email_history (email_status);
CREATE INDEX IF NOT EXISTS idx_email_history_offer_letter_id ON public.email_history (offer_letter_id);


-- ------------------------------------------------------------
-- 2. TABLE: public.campus_ambassador_history (CA Offer Letters)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.campus_ambassador_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    student_email TEXT NOT NULL,
    phone_number TEXT,
    college_name TEXT,
    internship_domain TEXT DEFAULT 'Campus Ambassador',
    internship_duration TEXT DEFAULT 'Tenure',
    start_date TEXT,
    end_date TEXT,
    offer_letter_type TEXT DEFAULT 'campus_ambassador',
    email_status TEXT DEFAULT 'pending',
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    offer_letter_id TEXT,
    pdf_filename TEXT,
    send_count INT DEFAULT 0,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_ca_history_created_at ON public.campus_ambassador_history (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ca_history_sent_at ON public.campus_ambassador_history (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_ca_history_student_email ON public.campus_ambassador_history (student_email);
CREATE INDEX IF NOT EXISTS idx_ca_history_email_status ON public.campus_ambassador_history (email_status);
CREATE INDEX IF NOT EXISTS idx_ca_history_offer_letter_id ON public.campus_ambassador_history (offer_letter_id);


-- ------------------------------------------------------------
-- 3. TABLE: public.certificate_history (Internship Certificates)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.certificate_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificate_id TEXT NOT NULL UNIQUE,
    student_name TEXT NOT NULL,
    student_email TEXT NOT NULL,
    internship_domain TEXT,
    start_date TEXT,
    end_date TEXT,
    issued_date TEXT,
    generated_date TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    email_status TEXT DEFAULT 'pending',
    sent_at TIMESTAMPTZ,
    send_count INT DEFAULT 0,
    pdf_filename TEXT,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_cert_history_created_at ON public.certificate_history (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cert_history_sent_at ON public.certificate_history (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_cert_history_student_email ON public.certificate_history (student_email);
CREATE INDEX IF NOT EXISTS idx_cert_history_email_status ON public.certificate_history (email_status);
CREATE INDEX IF NOT EXISTS idx_cert_history_certificate_id ON public.certificate_history (certificate_id);

-- ------------------------------------------------------------
-- 4. PERMISSIONS & SERVICE ROLE GRANTS
-- ------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.email_history TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.campus_ambassador_history TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.certificate_history TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
